In [1]:
import h5py
import json
import pandas as pd
import numpy as np
import torch
import os
import pickle
import ast
from data.loader import VQADataset
import linecache
import random
from datetime import datetime

In [4]:
dataset = VQADataset('train', True, False)
loader = torch.utils.data.DataLoader(dataset, 64, True, num_workers=4)

In [4]:
row

(tensor([ 6,  7,  8,  9, 10, 11, 12]),
 tensor([0.2165, 0.4433, 1.0576,  ..., 0.4351, 0.1685, 0.2410]),
 tensor([1652]))

In [3]:
x = [1,2,3,4,5,10, 234, 12314, 6,10]
%timeit dataset.__getitem__(random.choice(x))

426 µs ± 38.1 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
start = datetime.now()
for step, (x_nlp, x_img, t) in enumerate(loader):
    print(datetime.now()-start)
    start = datetime.now()

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 5 and 8 in dimension 1 at /Users/soumith/code/builder/wheel/pytorch-src/aten/src/TH/generic/THTensorMath.cpp:3616

In [5]:
[1,2,3] * 0

[]

In [6]:
os.cpu_count()

8